name: Conventional Commits

on:
  push:
    branches: [ master ]

jobs:
  cc:

    runs-on: ubuntu-latest

    timeout-minutes: 2

    steps:
      - name: Conventional Changelog Action
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          skip-commit: "true"