name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, development ]
  schedule:
    - cron: "0 0 * * *"
jobs:
  tests:

    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy .env file
        uses: canastro/copy-file-action@master
        with:
          source: '.env.actions'
          target: '.env'

      - name: Test
        run: npm run test-ci
        env:
          TW_CLIENT_ID: ${{ secrets.TW_CLIENT_ID }}
          TW_CLIENT_SECRET: ${{ secrets.TW_CLIENT_SECRET }}

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: Logs
          path: logs
